---
- name: Verify
  hosts: all
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Verify change-detection is running
      ansible.builtin.assert:
        that: >-
          ansible_facts['services']['change-detection.service']['state'] == 'running'
      become: true
